# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import iterm2_remote_pb2 as proto_dot_iterm2__remote__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/iterm2_remote_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Iterm2RemoteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnTerminal = channel.unary_unary(
                '/proto.Iterm2Remote/SpawnTerminal',
                request_serializer=proto_dot_iterm2__remote__pb2.SpawnTerminalRequest.SerializeToString,
                response_deserializer=proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
                _registered_method=True)
        self.SendToTerminal = channel.unary_unary(
                '/proto.Iterm2Remote/SendToTerminal',
                request_serializer=proto_dot_iterm2__remote__pb2.SendToTerminalRequest.SerializeToString,
                response_deserializer=proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
                _registered_method=True)
        self.JumpToTerminal = channel.unary_unary(
                '/proto.Iterm2Remote/JumpToTerminal',
                request_serializer=proto_dot_iterm2__remote__pb2.JumpToTerminalRequest.SerializeToString,
                response_deserializer=proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
                _registered_method=True)
        self.PeekTerminal = channel.unary_unary(
                '/proto.Iterm2Remote/PeekTerminal',
                request_serializer=proto_dot_iterm2__remote__pb2.PeekTerminalRequest.SerializeToString,
                response_deserializer=proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
                _registered_method=True)


class Iterm2RemoteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SpawnTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendToTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JumpToTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Iterm2RemoteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnTerminal,
                    request_deserializer=proto_dot_iterm2__remote__pb2.SpawnTerminalRequest.FromString,
                    response_serializer=proto_dot_iterm2__remote__pb2.DoRequestReply.SerializeToString,
            ),
            'SendToTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToTerminal,
                    request_deserializer=proto_dot_iterm2__remote__pb2.SendToTerminalRequest.FromString,
                    response_serializer=proto_dot_iterm2__remote__pb2.DoRequestReply.SerializeToString,
            ),
            'JumpToTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.JumpToTerminal,
                    request_deserializer=proto_dot_iterm2__remote__pb2.JumpToTerminalRequest.FromString,
                    response_serializer=proto_dot_iterm2__remote__pb2.DoRequestReply.SerializeToString,
            ),
            'PeekTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekTerminal,
                    request_deserializer=proto_dot_iterm2__remote__pb2.PeekTerminalRequest.FromString,
                    response_serializer=proto_dot_iterm2__remote__pb2.DoRequestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Iterm2Remote', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.Iterm2Remote', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Iterm2Remote(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SpawnTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Iterm2Remote/SpawnTerminal',
            proto_dot_iterm2__remote__pb2.SpawnTerminalRequest.SerializeToString,
            proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendToTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Iterm2Remote/SendToTerminal',
            proto_dot_iterm2__remote__pb2.SendToTerminalRequest.SerializeToString,
            proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JumpToTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Iterm2Remote/JumpToTerminal',
            proto_dot_iterm2__remote__pb2.JumpToTerminalRequest.SerializeToString,
            proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Iterm2Remote/PeekTerminal',
            proto_dot_iterm2__remote__pb2.PeekTerminalRequest.SerializeToString,
            proto_dot_iterm2__remote__pb2.DoRequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
