# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/iterm2_remote.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/iterm2_remote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/iterm2_remote.proto\x12\x05proto\"\xac\x01\n\x14SpawnTerminalRequest\x12\x1a\n\rterminal_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nfocus_term\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x12\n\x05shell\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07\x63ommand\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x10\n\x0e_terminal_nameB\r\n\x0b_focus_termB\x08\n\x06_shellB\n\n\x08_command\"]\n\x15SendToTerminalRequest\x12\x15\n\rterminal_name\x18\x01 \x01(\t\x12\x14\n\x0crequest_type\x18\x02 \x01(\t\x12\x17\n\x0frequest_content\x18\x03 \x01(\t\".\n\x15JumpToTerminalRequest\x12\x15\n\rterminal_name\x18\x01 \x01(\t\"V\n\x13PeekTerminalRequest\x12\x15\n\rterminal_name\x18\x02 \x01(\t\x12\x18\n\x0bpeek_length\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x0e\n\x0c_peek_length\":\n\x0e\x44oRequestReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2\xac\x02\n\x0cIterm2Remote\x12\x45\n\rSpawnTerminal\x12\x1b.proto.SpawnTerminalRequest\x1a\x15.proto.DoRequestReply\"\x00\x12G\n\x0eSendToTerminal\x12\x1c.proto.SendToTerminalRequest\x1a\x15.proto.DoRequestReply\"\x00\x12G\n\x0eJumpToTerminal\x12\x1c.proto.JumpToTerminalRequest\x1a\x15.proto.DoRequestReply\"\x00\x12\x43\n\x0cPeekTerminal\x12\x1a.proto.PeekTerminalRequest\x1a\x15.proto.DoRequestReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.iterm2_remote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPAWNTERMINALREQUEST']._serialized_start=37
  _globals['_SPAWNTERMINALREQUEST']._serialized_end=209
  _globals['_SENDTOTERMINALREQUEST']._serialized_start=211
  _globals['_SENDTOTERMINALREQUEST']._serialized_end=304
  _globals['_JUMPTOTERMINALREQUEST']._serialized_start=306
  _globals['_JUMPTOTERMINALREQUEST']._serialized_end=352
  _globals['_PEEKTERMINALREQUEST']._serialized_start=354
  _globals['_PEEKTERMINALREQUEST']._serialized_end=440
  _globals['_DOREQUESTREPLY']._serialized_start=442
  _globals['_DOREQUESTREPLY']._serialized_end=500
  _globals['_ITERM2REMOTE']._serialized_start=503
  _globals['_ITERM2REMOTE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
